### ISSUE TITLE
Hello,dose it support CreateDatastore type by geotiff? thanks

### ISSUE THREAD

**Issue by olongfen** [hishamkaram/geoserver#13]

**Comment by hishamkaram** [comment]
@olongfen sorry for late reply, this should be supported by this [PR](https://github.com/hishamkaram/geoserver/pull/11) but i don’t have time to check why the test fails

**Comment by hishamkaram** [comment]
@olongfen creating datastore from GeoTIFF file is not supported now but you can call [geoserver REST](https://docs.geoserver.org/latest/en/api/#1.0.0/datastores.yaml) to achieve that. Pull Requests are welcome

**Comment by olongfen** [comment]
> @olongfen creating datastore from GeoTIFF file is not supported now but you can call [geoserver REST](https://docs.geoserver.org/latest/en/api/#1.0.0/datastores.yaml) to achieve that. Pull Requests are welcome

i try achievet that, but i try command : 
``` curl -v -u admin:geoserver -XPUT -H "Content-type: image/tiff" --data-binary ./testdata.tif  http://localhost:8080/geoserver/rest/workspaces/geotiffWorkspace/datastores/testdata/file.geotiff```

but geoserver response: 
```* Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'admin'
> PUT /geoserver/rest/workspaces/geotiffWorkspace/datastores/testdata/file.geotiff HTTP/1.1
> Host: localhost:8080
> Authorization: Basic YWRtaW46Z2Vvc2VydmVy
> User-Agent: curl/7.68.0
> Accept: */*
> Content-type: image/tiff
> Content-Length: 14
> 
* upload completely sent off: 14 out of 14 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< X-Frame-Options: SAMEORIGIN
< Connection: close
< Server: Jetty(9.4.36.v20210114)
< 
* Closing connection 0
```
geoserver show: `org.geoserver.rest.RestException 400 BAD_REQUEST: Unsupported format: geotiff`

**Comment by hishamkaram** [comment]
@olongfen sorry for late reply , you need to do the following steps:
-  upload the geotiff to resources first  please check the api endpoints [here](https://docs.geoserver.org/latest/en/api/#1.0.0/resource.yaml)
-  create datastores through the API, please check the api endpoints [here](https://docs.geoserver.org/latest/en/api/#1.0.0/datastores.yaml)

**Comment by hishamkaram** [comment]
@olongfen please check this PR, feel free to open this issue again if it doesn’t work
https://github.com/hishamkaram/geoserver/pull/14
