### ISSUE TITLE
Cannot Customize http client

### ISSUE THREAD

**Issue by alienatorZ** [hishamkaram/geoserver#9]
If I try to connect to a geoserver with a self-signed cert geoserver fails. I suggest a way to customize the http client that the Geoserver struct is using. Currently it is unexported and I dont see a way to use a custom client if needed.

**Comment by hishamkaram** [comment]
@alienatorZ  sorry for late response I will add this feature next week!

**Comment by alienatorZ** [comment]
The latest works well. Thank you!
